# Setup
title:               shirokoiKR
tagline:             'shirokoi Korean language Patch'
description:         'shirokoi Korean language Patch'
url:                 http://shirokoiKR.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              shirokoi
  url:               https://twitter.com/KonagonaCoffee
  email:             shirokoikr@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
